version: '3.8'

services: 
  #Application tier service definition
  web: 
    build: 
    ports: 
      - "5000:5000"
    environment: 
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=devops_db
    depends_on: 
      db: 
        condition: service_healthy

    db: 
      image: mysql:8.0
      restart: always
      envitonment: 
        MYSQL_ROOT_PASSWORD: rootpassword
        MYSWQL_DATABASE: devops_db
      ports: 
        - "3306:3306"
      volumes: 
        - db_data:/var/lib/mysql
      healthcheck: 
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]  
        timeout: 20s
        retries: 10s

      volumes: 
        db_data:   
